# Generated by Django 5.1.5 on 2025-01-20 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playshelfapp', '0003_user_registration_date_alter_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registration_date',
        ),
    ]
